services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: kay
      MONGO_INITDB_ROOT_PASSWORD: secret

  backend:
    image: backend_img
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    

volumes:
  data:
  logs: